require 'bigdecimal'
require 'json'

require 'active_support/core_ext'
require 'core_ext'

require 'faraday'

require 'cmis/connection'
require 'cmis/exceptions'
require 'cmis/server'
require 'cmis/helpers'
require 'cmis/object_factory'
require 'cmis/query_result'
require 'cmis/query'
require 'cmis/children'
require 'cmis/relationships'
require 'cmis/repository'
require 'cmis/object'
require 'cmis/document'
require 'cmis/folder'
require 'cmis/item'
require 'cmis/policy'
require 'cmis/relationship'
require 'cmis/property_definition'
require 'cmis/type'
require 'cmis/version'
