---
local:
  server:
    service_url: http://33.33.33.100:8080/browser
  repository: test
nuxeo:
  server:
    service_url: http://cmis.demo.nuxeo.com/nuxeo/json/cmis
    username: Administrator
    password: Administrator
  repository: default
alfresco:
  server:
    service_url: http://cmis.alfresco.com/cmisbrowser
    username: admin
    password: admin
  repository: bb212ecb-122d-47ea-b5c1-128affb9cd8f
